import React from 'react'
import Home from './pages/Home';
import coverAespa from './assets/Aespa.jpg'
import coverNmixx from './assets/Nmixx.jpg'
import coverIve from './assets/IVE.jpg'
import coverCortis from './assets/Cortis.jpg'
import coverZico from './assets/Zico.jpg'
import coverBabyMon from './assets/ChooM.jpg'
import coverTK from './assets/TK.jpg'
import coverAi from './assets/Ai.jpg'
import coverLiSA from './assets/LiSA.jpg'
import coverYoaSobi from './assets/Yoa.jpg'
import coverCreepy from './assets/creepy.jpg'
import coverFuziKaze from './assets/FZK.jpg'
import coverPhantom from './assets/phantom.jpg'
import coverKenshi from './assets/yonezu.jpg'
import coverSawano from './assets/Sawano.jpg'
import coverImase from './assets/Imase.jpg'
import coverImagine from './assets/Dragons.jpg'
import coverEd from './assets/Ed.jpg'
import coverDua from './assets/dua.jpg'
import coverHarry from './assets/Harry.jpg'
import coverOlivia from './assets/olivia.jpg'
import coverWeeknd from './assets/weeknd.jpg'
import coverArijit from './assets/Arijit.jpg'
import coverAditya from './assets/Paaro.jpg'
import coverMohit from './assets/mohit.jpg'
import coverJasleen from './assets/Ranjha.jpg'
import coverKushagra from './assets/Finding.jpg'
import coverAnuv from './assets/Anuv.jpg'
import coverTalwinder from './assets/Talwinder.jpg'
import coverHindiPop from './assets/hpop.jpg'
import coverKorean from './assets/korCover.jpg'
import coverHindi from './assets/anyCover.jpg'
import coverEnglish from './assets/playCover.jpg'
import coverJapanese from './assets/newCover.jpg'
import coverKarina from './assets/karina.jpg'
import coverBite from './assets/lemonade.jpg'
import coverSSak from './assets/oxy.jpg'
import coverCrush from './assets/crush.jpg'
import coverAdvice from './assets/advice.jpg'
import coverH2H from './assets/Hearts2Hearts.jpg'
import coverYena from './assets/yena.jpg'
import coverLeela from './assets/oxy.jpg'
import coverIdle from './assets/Idle.jpg'
import coverLngshot from './assets/LNGSHOT.jpg'
import coverBts from './assets/bts.jpg'
import coverBlkpink from './assets/BLACKPINK.jpg'
import coverMeovv from './assets/MEOVV.jpg'
import coverIllit from './assets/ILLIT.jpg'
import coverHeavy from './assets/heavy.jpg'
import coverAteez from './assets/ATEEZ.jpg'
import coverStray from './assets/stray.jpg'
import coverEnhypen from './assets/ENHYPEN.jpg'
import coverJisoo from './assets/jisoo.jpg'
import coverSooyah from './assets/sooyah.jpg'
import coverIvena from './assets/IHAVE.jpg'
import coverSSERA from './assets/lessera.jpg'
import coverSeven from './assets/Seventeen.jpg'
import cover404 from './assets/404.jpg'
import coverBatterUp from './assets/batter.jpg'
import coverWhiplash from './assets/whiplash.jpg'
import coverDrama from './assets/DRAMA.jpg'
import coverLess from './assets/lessera.jpg'


const App = () => {

  const songs = [

    {
      id: 1,
      title: "LEMONADE",
      artist: "aespa",
      subGenre: "K-Pop",
      album: "LEMONADE",
      albumType: "Album",
      coverImage: coverBite,
    },
    {
      id: 2,
      title: "WDA (Whole Different Animal)",
      artist: "aespa",
      subGenre: "K-Pop",
      album: "LEMONADE",
      albumType: "Album",
      coverImage: coverBite,
    },
    {
      id: 3,
      title: "BLACKHOLE",
      artist: "IVE",
      subGenre: "K-Pop",
      album: "REVIVE+",
      albumType: "Album",
      coverImage: coverIve,
    },
    {
      id: 4,
      title: "Bang Bang",
      artist: "IVE",
      subGenre: "K-Pop",
      album: "REVIVE+",
      albumType: "Album",
      coverImage: coverIve,
    },
    {
      id: 5,
      title: "Heavy Serenade",
      artist: "NMIXX",
      subGenre: "K-Pop",
      album: "Heavy Serenade",
      albumType: "EP",
      coverImage: coverNmixx,
    },
    {
      id: 6,
      title: "Crescendo",
      artist: "NMIXX",
      subGenre: "K-Pop",
      album: "Heavy Serenade",
      albumType: "EP",
      coverImage: coverNmixx,
    },
    {
      id: 7,
      title: "CHOOM",
      artist: "BABYMONSTER",
      subGenre: "K-Pop",
      album: "CHOOM",
      albumType: "EP",
      coverImage: coverBabyMon,
    },
    {
      id: 8,
      title: "SUGAR HONEY ICE TEA",
      artist: "BABYMONSTER",
      subGenre: "K-Pop",
      album: "SUGAR HONEY ICE TEA",
      albumType: "Single",
      coverImage: coverBabyMon,
    },
    {
      id: 9,
      title: "REDRED",
      artist: "CORTIS",
      subGenre: "K-Pop",
      album: "GREENGREEN",
      albumType: "EP",
      coverImage: coverCortis,
    },
    {
      id: 10,
      title: "TNT",
      artist: "CORTIS",
      subGenre: "K-Pop",
      album: "GREENGREEN",
      albumType: "EP",
      coverImage: coverCortis,
    },
    {
      id: 11,
      title: "Matsuri",
      artist: "Fujii Kaze",
      subGenre: "J-Pop",
      album: "LOVE ALL SERVE ALL",
      albumType: "Album",
      coverImage: coverFuziKaze,
    },
    {
      id: 12,
      title: "Otomodachi",
      artist: "Phantom Siita",
      subGenre: "J-Pop",
      album: "Shoujo no Hi no Omoide",
      albumType: "Album",
      coverImage: coverPhantom,
    },
    {
      id: 13,
      title: "Blue Diary",
      artist: "Ai Tomioka",
      subGenre: "J-Pop",
      album: "Ai's Cream",
      albumType: "Album",
      coverImage: coverAi,
    },
    {
      id: 14,
      title: "Idol",
      artist: "YOASOBI",
      subGenre: "J-Pop",
      album: "Idol",
      albumType: "Single",
      coverImage: coverYoaSobi,
    },
    {
      id: 15,
      title: "Otonoke",
      artist: "Creepy Nuts",
      subGenre: "J-Pop",
      album: "Otonoke",
      albumType: "Single",
      coverImage: coverCreepy,
    },
    {
      id: 16,
      title: "Iris Out",
      artist: "Kenshi Yonezu",
      subGenre: "J-Pop",
      album: "Lost Corner",
      albumType: "Album",
      coverImage: coverKenshi,
    },
    {
      id: 17,
      title: "Unravel",
      artist: "TK from Ling Tosite Sigure",
      subGenre: "J-Pop",
      album: "Fantastic Magic",
      albumType: "Album",
      coverImage: coverTK,
    },
    {
      id: 18,
      title: "Gurenge",
      artist: "LiSA",
      subGenre: "J-Pop",
      album: "LEO-NiNE",
      albumType: "Album",
      coverImage: coverLiSA,
    },
    {
      id: 19,
      title: "Shinunoga E-Wa",
      artist: "Fujii Kaze",
      subGenre: "J-Pop",
      album: "HELP EVER HURT NEVER",
      albumType: "Album",
      coverImage: coverFuziKaze,
    },
    {
      id: 20,
      title: "Bling-Bang-Bang-Born",
      artist: "Creepy Nuts",
      subGenre: "J-Pop",
      album: "Bling-Bang-Bang-Born",
      albumType: "Single",
      coverImage: coverCreepy,
    },
    {
      id: 21,
      title: "Kesariya",
      artist: "Arijit Singh",
      subGenre: "Hindi Pop",
      album: "Brahmāstra",
      albumType: "Album",
      coverImage: coverHindiPop,
    },
    {
      id: 22,
      title: "Heeriye",
      artist: "Arijit Singh",
      subGenre: "Hindi Pop",
      album: "Heeriye",
      albumType: "Single",
      coverImage: coverArijit,
    },
    {
      id: 23,
      title: "Jo Tum Mere Ho",
      artist: "Anuv Jain",
      subGenre: "Hindi Pop",
      album: "Jo Tum Mere Ho",
      albumType: "Single",
      coverImage: coverAnuv,
    },
    {
      id: 24,
      title: "Husn",
      artist: "Anuv Jain",
      subGenre: "Hindi Pop",
      album: "Husn",
      albumType: "Single",
      coverImage: coverAnuv,
    },
    {
      id: 25,
      title: "Sahiba",
      artist: "Aditya Rikhari",
      subGenre: "Hindi Pop",
      album: "Sahiba",
      albumType: "Single",
      coverImage: coverAditya,
    },
    {
      id: 26,
      title: "Apna Bana Le",
      artist: "Arijit Singh",
      subGenre: "Hindi Pop",
      album: "Bhediya",
      albumType: "Album",
      coverImage: coverHindiPop,
    },
    {
      id: 27,
      title: "Ranjha",
      artist: "Jasleen Royal",
      subGenre: "Hindi Pop",
      album: "Shershaah",
      albumType: "Album",
      coverImage: coverJasleen,
    },
    {
      id: 28,
      title: "Tum Se Hi",
      artist: "Mohit Chauhan",
      subGenre: "Hindi Pop",
      album: "Jab We Met",
      albumType: "Album",
      coverImage: coverMohit,
    },
    {
      id: 29,
      title: "Tum Hi Ho",
      artist: "Arijit Singh",
      subGenre: "Hindi Pop",
      album: "Aashiqui 2",
      albumType: "Album",
      coverImage: coverArijit,
    },
    {
      id: 30,
      title: "Finding Her",
      artist: "Kushagra",
      subGenre: "Hindi Pop",
      album: "Finding Her",
      albumType: "Single",
      coverImage: coverKushagra,
    },
    {
      id: 31,
      title: "Blinding Lights",
      artist: "The Weeknd",
      subGenre: "English Pop",
      album: "After Hours",
      albumType: "Album",
      coverImage: coverWeeknd,
    },
    {
      id: 32,
      title: "Die For You",
      artist: "The Weeknd",
      subGenre: "English Pop",
      album: "Starboy",
      albumType: "Album",
      coverImage: coverWeeknd,
    },
    {
      id: 33,
      title: "As It Was",
      artist: "Harry Styles",
      subGenre: "English Pop",
      album: "Harry's House",
      albumType: "Album",
      coverImage: coverHarry,
    },
    {
      id: 34,
      title: "Watermelon Sugar",
      artist: "Harry Styles",
      subGenre: "English Pop",
      album: "Fine Line",
      albumType: "Album",
      coverImage: coverHarry,
    },
    {
      id: 35,
      title: "Levitating",
      artist: "Dua Lipa",
      subGenre: "English Pop",
      album: "Future Nostalgia",
      albumType: "Album",
      coverImage: coverDua,
    },
    {
      id: 36,
      title: "Physical",
      artist: "Dua Lipa",
      subGenre: "English Pop",
      album: "Future Nostalgia",
      albumType: "Album",
      coverImage: coverDua,
    },
    {
      id: 37,
      title: "Perfect",
      artist: "Ed Sheeran",
      subGenre: "English Pop",
      album: "÷ (Divide)",
      albumType: "Album",
      coverImage: coverEd,
    },
    {
      id: 38,
      title: "Photograph",
      artist: "Ed Sheeran",
      subGenre: "English Pop",
      album: "× (Multiply)",
      albumType: "Album",
      coverImage: coverEd,
    },
    {
      id: 39,
      title: "So Easy",
      artist: "Olivia Dean",
      subGenre: "English Pop",
      album: "The Art of Loving",
      albumType: "Album",
      coverImage: coverOlivia,
    },
    {
      id: 40,
      title: "Believer",
      artist: "Imagine Dragons",
      subGenre: "English Pop",
      album: "Evolve",
      albumType: "Album",
      coverImage: coverImagine,
    },
    {
      id: 41,
      title: "Any Song",
      artist: "Zico",
      subGenre: "K-Pop",
      album: "Any Song",
      albumType: "Single",
      coverImage: coverZico,
    },
    {
      id: 42,
      title: "Whiplash",
      artist: "aespa",
      subGenre: "K-Pop",
      album: "Whiplash",
      albumType: "EP",
      coverImage: coverWhiplash,
    },
    {
      id: 43,
      title: "Armageddon",
      artist: "aespa",
      subGenre: "K-Pop",
      album: "Armageddon",
      albumType: "Album",
      coverImage: coverAespa,
    },
    {
      id: 44,
      title: "Night Dancer",
      artist: "imase",
      subGenre: "J-Pop",
      album: "Night Dancer",
      albumType: "Single",
      coverImage: coverImase,
    },
    {
      id: 45,
      title: "Inertia",
      artist: "Sawano Hiroyuki",
      subGenre: "J-Pop",
      album: "Inertia",
      albumType: "Single",
      coverImage: coverSawano,
    },
    {
      id: 46,
      title: "Haseen",
      artist: "Talwinder",
      subGenre: "Hindi Pop",
      album: "Haseen",
      albumType: "Single",
      coverImage: coverTalwinder,
    },
    {
      id: 47,
      title: "UP",
      artist: "KARINA",
      subGenre: "K-Pop",
      album: "UP",
      albumType: "Single",
      coverImage: coverKarina,
    },
    {
      id: 48,
      title: "Good Stuff",
      artist: "KARINA",
      subGenre: "K-Pop",
      album: "Good Stuff",
      albumType: "Single",
      coverImage: coverKarina,
    },
    {
      id: 49,
      title: "BITE",
      artist: "aespa",
      subGenre: "K-Pop",
      album: "BITE",
      albumType: "Single",
      coverImage: coverBite,
    },
    {
      id: 50,
      title: "Spicy",
      artist: "aespa",
      subGenre: "K-Pop",
      album: "MY WORLD",
      albumType: "EP",
      coverImage: coverWhiplash,
    },
    {
      id: 51,
      title: "Supernova",
      artist: "aespa",
      subGenre: "K-Pop",
      album: "Armageddon",
      albumType: "Album",
      coverImage: coverWhiplash,
    },
    {
      id: 52,
      title: "Licorice",
      artist: "aespa",
      subGenre: "K-Pop",
      album: "Armageddon",
      albumType: "Album",
      coverImage: coverWhiplash,
    },
    {
      id: 53,
      title: "Drama",
      artist: "aespa",
      subGenre: "K-Pop",
      album: "Drama",
      albumType: "EP",
      coverImage: coverDrama,
    },
    {
      id: 54,
      title: "SSAK (feat. LOGO)",
      artist: "Oxynova",
      subGenre: "K-Pop",
      album: "SSAK",
      albumType: "Single",
      coverImage: coverSSak,
    },
    {
      id: 55,
      title: "Ego",
      artist: "Crush",
      subGenre: "K-Pop",
      album: "Ego",
      albumType: "Single",
      coverImage: coverCrush,
    },
    {
      id: 56,
      title: "Advice",
      artist: "TAEMIN",
      subGenre: "K-Pop",
      album: "Advice",
      albumType: "EP",
      coverImage: coverAdvice,
    },
    {
      id: 57,
      title: "RUDE",
      artist: "Hearts2Hearts",
      subGenre: "K-Pop",
      album: "RUDE",
      albumType: "Single",
      coverImage: coverH2H,
    },
    {
      id: 58,
      title: "Catch Catch",
      artist: "YENA",
      subGenre: "K-Pop",
      album: "Catch Catch",
      albumType: "Single",
      coverImage: coverYena,
    },
    {
      id: 59,
      title: "Mono (feat. skaiwater)",
      artist: "i-dle",
      subGenre: "K-Pop",
      album: "Mono",
      albumType: "Single",
      coverImage: coverIdle,
    },
    {
      id: 60,
      title: "Don't Do That",
      artist: "Leellamarz",
      subGenre: "K-Pop",
      album: "Don't Do That",
      albumType: "Single",
      coverImage: coverSSak,
    },
    {
      id: 61,
      title: "Moonwalkin'",
      artist: "Lngshot",
      subGenre: "K-Pop",
      album: "Moonwalkin'",
      albumType: "Single",
      coverImage: coverLngshot,
    },
    {
      id: 62,
      title: "Hands Up",
      artist: "MEOVV",
      subGenre: "K-Pop",
      album: "Hands Up",
      albumType: "Single",
      coverImage: coverMeovv,
    },
    {
      id: 63,
      title: "Burnin' Up",
      artist: "MEOVV",
      subGenre: "K-Pop",
      album: "Burnin' Up",
      albumType: "Single",
      coverImage: coverMeovv,
    },
    {
      id: 64,
      title: "Body",
      artist: "MEOVV",
      subGenre: "K-Pop",
      album: "Body",
      albumType: "Single",
      coverImage: coverMeovv,
    },
    {
      id: 65,
      title: "Blue Valentine",
      artist: "NMIXX",
      subGenre: "K-Pop",
      album: "Blue Valentine",
      albumType: "Single",
      coverImage: coverHeavy,
    },
    {
      id: 66,
      title: "iDeserveIt",
      artist: "NMIXX",
      subGenre: "K-Pop",
      album: "iDeserveIt",
      albumType: "Single",
      coverImage: coverHeavy,
    },
    {
      id: 67,
      title: "Not Cute Anymore",
      artist: "ILLIT",
      subGenre: "K-Pop",
      album: "Not Cute Anymore",
      albumType: "Single",
      coverImage: coverIllit,
    },
    {
      id: 68,
      title: "JUMP",
      artist: "BLACKPINK",
      subGenre: "K-Pop",
      album: "JUMP",
      albumType: "Single",
      coverImage: coverBlkpink,
    },
    {
      id: 69,
      title: "Shut Down",
      artist: "BLACKPINK",
      subGenre: "K-Pop",
      album: "BORN PINK",
      albumType: "Album",
      coverImage: coverBlkpink,
    },
    {
      id: 70,
      title: "APT.",
      artist: "ROSÉ",
      subGenre: "K-Pop",
      album: "APT.",
      albumType: "Single",
      coverImage: coverBlkpink,
    },
    {
      id: 71,
      title: "It's Me",
      artist: "ILLIT",
      subGenre: "K-Pop",
      album: "It's Me",
      albumType: "Single",
      coverImage: coverIllit,
    },
    {
      id: 72,
      title: "Adrenaline",
      artist: "ATEEZ",
      subGenre: "K-Pop",
      album: "Adrenaline",
      albumType: "Single",
      coverImage: coverAteez,
    },
    {
      id: 73,
      title: "Body To Body",
      artist: "BTS",
      subGenre: "K-Pop",
      album: "Body To Body",
      albumType: "Single",
      coverImage: coverBts,
    },
    {
      id: 74,
      title: "Swim",
      artist: "BTS",
      subGenre: "K-Pop",
      album: "Swim",
      albumType: "Single",
      coverImage: coverBts,
    },
    {
      id: 75,
      title: "Aliens",
      artist: "BTS",
      subGenre: "K-Pop",
      album: "Aliens",
      albumType: "Single",
      coverImage: coverBts,
    },
    {
      id: 76,
      title: "Thunderous",
      artist: "Stray Kids",
      subGenre: "K-Pop",
      album: "NOEASY",
      albumType: "Album",
      coverImage: coverStray,
    },
    {
      id: 77,
      title: "Chk Chk Boom",
      artist: "Stray Kids",
      subGenre: "K-Pop",
      album: "ATE",
      albumType: "EP",
      coverImage: coverStray,
    },
    {
      id: 78,
      title: "Acai",
      artist: "Cortis",
      subGenre: "K-Pop",
      album: "Acai",
      albumType: "Single",
      coverImage: coverCortis,
    },
    {
      id: 79,
      title: "Tick-Tack",
      artist: "ILLIT",
      subGenre: "K-Pop",
      album: "Tick-Tack",
      albumType: "Single",
      coverImage: coverIllit,
    },
    {
      id: 80,
      title: "404 (New Era)",
      artist: "KiiiKiii",
      subGenre: "K-Pop",
      album: "404 (New Era)",
      albumType: "Single",
      coverImage: cover404,
    },
    {
      id: 81,
      title: "Earthquake",
      artist: "JISOO",
      subGenre: "K-Pop",
      album: "AMORTAGE",
      albumType: "EP",
      coverImage: coverJisoo,
    },
    {
      id: 82,
      title: "Tears",
      artist: "JISOO",
      subGenre: "K-Pop",
      album: "AMORTAGE",
      albumType: "EP",
      coverImage: coverJisoo,
    },
    {
      id: 83,
      title: "Flower",
      artist: "JISOO",
      subGenre: "K-Pop",
      album: "ME",
      albumType: "Single Album",
      coverImage: coverSooyah,
    },
    {
      id: 84,
      title: "All Eyes On Me",
      artist: "JISOO",
      subGenre: "K-Pop",
      album: "ME",
      albumType: "Single Album",
      coverImage: coverSooyah,
    },
    {
      id: 85,
      title: "Knife",
      artist: "ENHYPEN",
      subGenre: "K-Pop",
      album: "Knife",
      albumType: "Single",
      coverImage: coverEnhypen,
    },
    {
      id: 86,
      title: "Bite Me",
      artist: "ENHYPEN",
      subGenre: "K-Pop",
      album: "DARK BLOOD",
      albumType: "EP",
      coverImage: coverEnhypen,
    },
    {
      id: 87,
      title: "BAD",
      artist: "ATEEZ",
      subGenre: "K-Pop",
      album: "BAD",
      albumType: "Single",
      coverImage: coverAteez,
    },
    {
      id: 88,
      title: "I AM",
      artist: "IVE",
      subGenre: "K-Pop",
      album: "I've IVE",
      albumType: "Album",
      coverImage: coverIvena,
    },
    {
      id: 89,
      title: "BATTER UP",
      artist: "BABYMONSTER",
      subGenre: "K-Pop",
      album: "BATTER UP",
      albumType: "Single",
      coverImage: coverBatterUp,
    },
    {
      id: 90,
      title: "ANTIFRAGILE",
      artist: "LE SSERAFIM",
      subGenre: "K-Pop",
      album: "ANTIFRAGILE",
      albumType: "EP",
      coverImage: coverLess,
    },
    {
      id: 91,
      title: "CRAZY",
      artist: "LE SSERAFIM",
      subGenre: "K-Pop",
      album: "CRAZY",
      albumType: "EP",
      coverImage: coverLess,
    },
    {
      id: 92,
      title: "Spaghetti",
      artist: "LE SSERAFIM",
      subGenre: "K-Pop",
      album: "Spaghetti",
      albumType: "Single",
      coverImage: coverLess,
    },
    {
      id: 93,
      title: "Butter",
      artist: "BTS",
      subGenre: "K-Pop",
      album: "Butter",
      albumType: "Single",
      coverImage: coverBts,
    },
    {
      id: 94,
      title: "No Doubt",
      artist: "ENHYPEN",
      subGenre: "K-Pop",
      album: "ROMANCE : UNTOLD",
      albumType: "Album",
      coverImage: coverEnhypen,
    },
    {
      id: 95,
      title: "Super",
      artist: "SEVENTEEN",
      subGenre: "K-Pop",
      album: "FML",
      albumType: "EP",
      coverImage: coverSeven,
    },


  ];

  const playlists = [
    {
      id: 1,
      title: "K-Pop",
      cover: coverKorean,
      songs: songs.filter(song => song.subGenre === "K-Pop"),
    },
    {
      id: 2,
      title: "English Pop",
      cover: coverEnglish,
      songs: songs.filter(song => song.subGenre === "English Pop"),
    },
    {
      id: 3,
      title: "Hindi Pop",
      cover: coverHindi,
      songs: songs.filter(song => song.subGenre === "Hindi Pop"),
    },

    {
      id: 4,
      title: "J-Pop",
      cover: coverJapanese,
      songs: songs.filter(song => song.subGenre === "J-Pop"),
    },



  ];

  return (
    <Home songs={songs} playlists={playlists} />

  )
}

export default App


